version: '3.8'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_VERSION=3.5.3
      - SPARK_MODE=master
    ports:
      - "8080:8080"   # Spark UI
      - "7077:7077"   # Spark master port
    volumes:
      - spark-data:/bitnami/spark
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_VERSION=3.5.3
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    volumes:
      - spark-data:/bitnami/spark
    networks:
      - spark-network

  python-app:
    build: ./app
    container_name: python-spark-app
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - ./app:/app
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - spark-network


volumes:
  spark-data:

networks:
  spark-network:
    driver: bridge
